### ISSUE TITLE
Connection to relay fails

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/libp2p-relay#8]
Starting the echodeamon and connecting to the relay panics with:

```
panic: Can not create a new relayFinder. Need a Peer Source fn or a list of static relays. Refer to the documentation around `libp2p.EnableAutoRelay`

goroutine 1 [running]:
github.com/libp2p/go-libp2p/p2p/host/autorelay.newRelayFinder(0x147ca10?, 0xc000190000?, 0xc0000143a0?)
	/home/dylan/go/pkg/mod/github.com/libp2p/go-libp2p@v0.26.0/p2p/host/autorelay/relay_finder.go:84 +0x234
github.com/libp2p/go-libp2p/p2p/host/autorelay.NewAutoRelay(0xc000002780, {0x0, 0x0, 0x10?})
	/home/dylan/go/pkg/mod/github.com/libp2p/go-libp2p@v0.26.0/p2p/host/autorelay/autorelay.go:49 +0x1a5
github.com/libp2p/go-libp2p/config.(*Config).NewNode(0xc000319000)
	/home/dylan/go/pkg/mod/github.com/libp2p/go-libp2p@v0.26.0/config/config.go:354 +0x3cc
github.com/libp2p/go-libp2p.NewWithoutDefaults({0xc000366f80, 0x8, 0x8})
	/home/dylan/go/pkg/mod/github.com/libp2p/go-libp2p@v0.26.0/libp2p.go:67 +0x6b
github.com/libp2p/go-libp2p.New(...)
	/home/dylan/go/pkg/mod/github.com/libp2p/go-libp2p@v0.26.0/libp2p.go:53
github.com/threefoldtech/libp2p-relay/client.CreateLibp2pHost({0x147ca10?, 0xc000190000}, 0x12333e4?, 0x1, {0xc000050880, 0x20, 0x40}, {0x0?, 0x0}, {0xc00037aa20, ...})
	/home/dylan/Projects/libp2p-relay/client/p2p.go:76 +0x756
main.main()
	/home/dylan/Projects/libp2p-relay/examples/echodaemon/main.go:86 +0x6ce

```

**Comment by DylanVerstraete** [comment]
fixed in https://github.com/threefoldtech/libp2p-relay/pull/7

**Comment by robvanmieghem** [comment]
#7  has some flaws that need to be adressed, looking into using autoRelay

**Comment by robvanmieghem** [comment]
ed196a726262f62656ebb5286340ae400ec24272
